[[profile]]
name = "current_20260112"

[[profile.output]]
enable = true
search = ["m=SV340ZD", "s=", "v=PNP(QHX)"]
mode = "3440x1440@144Hz"
position = "0,906"
scale = 1.0
transform = "normal"
adaptive_sync = false

[[profile.output]]
enable = true
search = ["m=DELL P2419H", "s=9RSH993", "v=Dell Inc."]
mode = "1920x1080@60Hz"
position = "3440,1362"
scale = 1.09765625
transform = "normal"
adaptive_sync = false

