shell = "zsh"

[plugins]

# プラグインの遅延読み込み
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# apply = ["defer"] で遅延読み込み対象のプラグインを指定
[templates]
defer = "{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

# シンタックスハイライト
[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"
apply = ["defer"]